// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.vicras.proto_gen.auth;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Credentials_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Credentials_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Token_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Token_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\032\033google/protobuf/empty.prot" +
      "o\032\036google/protobuf/wrappers.proto\".\n\013Cre" +
      "dentials\022\020\n\010password\030\001 \001(\t\022\r\n\005login\030\002 \001(" +
      "\t\"\026\n\005Login\022\r\n\005login\030\001 \001(\t\"\026\n\005Token\022\r\n\005to" +
      "ken\030\001 \001(\t\"\033\n\010Response\022\017\n\007message\030\001 \001(\t\"3" +
      "\n\004User\022\r\n\005login\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022" +
      "\n\n\002id\030\003 \001(\t2\344\001\n\016AuthController\022!\n\016getUse" +
      "rByLogin\022\006.Login\032\005.User\"\000\022!\n\016getUserByTo" +
      "ken\022\006.Token\032\005.User\"\000\0222\n\010saveUser\022\014.Crede" +
      "ntials\032\026.google.protobuf.Empty\"\000\022\"\n\010getT" +
      "oken\022\014.Credentials\032\006.Token\"\000\0224\n\014isTokenV" +
      "alid\022\006.Token\032\032.google.protobuf.BoolValue" +
      "\"\000B\035\n\031com.vicras.proto_gen.authP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_Credentials_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Credentials_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Credentials_descriptor,
        new java.lang.String[] { "Password", "Login", });
    internal_static_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_descriptor,
        new java.lang.String[] { "Login", });
    internal_static_Token_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Token_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Login", "Password", "Id", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
