// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.vicras.proto_gen.auth;

public interface CredentialsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Credentials)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string login = 2;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>string login = 2;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();
}
