// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.vicras.proto_gen.auth;

public interface LoginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Login)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string login = 1;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>string login = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();
}
