// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.vicras.proto_gen.auth;

public interface TokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Token)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
