// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.vicras.proto_gen.auth;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string login = 1;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>string login = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string id = 3;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 3;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
