server:
  port: 3351

spring:
  application:
    name: gateway

grpc:
  user: ${GRPC_USER:user}
  password: ${GRPC_PASSWORD:password}
  client:
    user-grpc-server:
      address: static://localhost:3352
      negotiationType: plaintext
    note-grpc-server:
      address: static://localhost:3353
      negotiationType: plaintext
