// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: note.proto

package com.vicras.proto_gen.note;

public interface NotesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Notes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Note notes = 1;</code>
   */
  java.util.List<com.vicras.proto_gen.note.Note> 
      getNotesList();
  /**
   * <code>repeated .Note notes = 1;</code>
   */
  com.vicras.proto_gen.note.Note getNotes(int index);
  /**
   * <code>repeated .Note notes = 1;</code>
   */
  int getNotesCount();
  /**
   * <code>repeated .Note notes = 1;</code>
   */
  java.util.List<? extends com.vicras.proto_gen.note.NoteOrBuilder> 
      getNotesOrBuilderList();
  /**
   * <code>repeated .Note notes = 1;</code>
   */
  com.vicras.proto_gen.note.NoteOrBuilder getNotesOrBuilder(
      int index);
}
