// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: note.proto

package com.vicras.proto_gen.note;

public final class NoteOuterClass {
  private NoteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Note_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Note_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Notes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnote.proto\032\033google/protobuf/empty.prot" +
      "o\032\036google/protobuf/wrappers.proto\"E\n\004Not" +
      "e\022\n\n\002id\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\020\n\010questio" +
      "n\030\003 \001(\t\022\017\n\007answers\030\004 \003(\t\"\035\n\005Notes\022\024\n\005not" +
      "es\030\001 \003(\0132\005.Note2\355\001\n\016NoteController\022,\n\tne" +
      "wRecord\022\005.Note\032\026.google.protobuf.Empty\"\000" +
      "\022/\n\007getById\022\033.google.protobuf.Int64Value" +
      "\032\005.Note\"\000\0227\n\016getAllByUserId\022\033.google.pro" +
      "tobuf.Int64Value\032\006.Notes\"\000\022C\n\ndeleteById" +
      "\022\033.google.protobuf.Int64Value\032\026.google.p" +
      "rotobuf.Empty\"\000B\035\n\031com.vicras.proto_gen." +
      "noteP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_Note_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Note_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Note_descriptor,
        new java.lang.String[] { "Id", "UserId", "Question", "Answers", });
    internal_static_Notes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Notes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Notes_descriptor,
        new java.lang.String[] { "Notes", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
