// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: note.proto

package com.vicras.proto_gen.note;

public interface NoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Note)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 userId = 2;</code>
   */
  long getUserId();

  /**
   * <code>string question = 3;</code>
   */
  java.lang.String getQuestion();
  /**
   * <code>string question = 3;</code>
   */
  com.google.protobuf.ByteString
      getQuestionBytes();

  /**
   * <code>repeated string answers = 4;</code>
   */
  java.util.List<java.lang.String>
      getAnswersList();
  /**
   * <code>repeated string answers = 4;</code>
   */
  int getAnswersCount();
  /**
   * <code>repeated string answers = 4;</code>
   */
  java.lang.String getAnswers(int index);
  /**
   * <code>repeated string answers = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnswersBytes(int index);
}
